// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBup9SuOF4_00eEZAHT2ZPnAXGHXMo-SiU',
    appId: '1:521575929980:web:abbcfeb97215b8a391d1f9',
    messagingSenderId: '521575929980',
    projectId: 'fir-7ea46',
    authDomain: 'fir-7ea46.firebaseapp.com',
    storageBucket: 'fir-7ea46.firebasestorage.app',
    measurementId: 'G-RQKP2E30VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJiLGzHy7GDXP_FuuYCNuMFDKbP41fQPk',
    appId: '1:521575929980:android:6c0769759366d2e791d1f9',
    messagingSenderId: '521575929980',
    projectId: 'fir-7ea46',
    storageBucket: 'fir-7ea46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApG-iYHFjAz7ZUn74FczTK0_tGSKtX6CA',
    appId: '1:521575929980:ios:ba348addc038f78391d1f9',
    messagingSenderId: '521575929980',
    projectId: 'fir-7ea46',
    storageBucket: 'fir-7ea46.firebasestorage.app',
    iosBundleId: 'com.example.menubar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApG-iYHFjAz7ZUn74FczTK0_tGSKtX6CA',
    appId: '1:521575929980:ios:ba348addc038f78391d1f9',
    messagingSenderId: '521575929980',
    projectId: 'fir-7ea46',
    storageBucket: 'fir-7ea46.firebasestorage.app',
    iosBundleId: 'com.example.menubar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBup9SuOF4_00eEZAHT2ZPnAXGHXMo-SiU',
    appId: '1:521575929980:web:e518ca16629b1f5e91d1f9',
    messagingSenderId: '521575929980',
    projectId: 'fir-7ea46',
    authDomain: 'fir-7ea46.firebaseapp.com',
    storageBucket: 'fir-7ea46.firebasestorage.app',
    measurementId: 'G-QB15GJ893R',
  );
}
